// rxjs-with-svelte/src/lib/views/App.svelte
<script lang="ts">
  import { swapiData, swapiActions, showLoading } from '../stores/swapiStore';

  import Header from '../components/Header.svelte';
</script>

<main>
  <h1>Star Wars People</h1>
  <button on:click={() => swapiActions.getPeople()}>Fetch them</button>
  {#if $showLoading}
    <p>Loading...</p>
  {:else if $swapiData.status === 'error'}
    <p>Yikes, we ran into some trouble. Try again, please</p>
  {:else if $swapiData.status === 'fetching' || $swapiData.status === 'loaded'}
    <ul>
      {#each $swapiData.data as person (person.name)}
        <li>{person.name}</li>
      {/each}
    </ul>
  {/if}
</main>
<div class="header">
  <Header />
</div>

<style>
  div.header {
    position: absolute;
    top: 16px;
    right: 16px;
  }
  
  ul {
    padding: 0;
  }

  li {
    list-style: none;
  }
</style>

// rxjs-with-angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { SwapiService } from './services/swapi.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(public swapiService: SwapiService) {}
}

<main>
  <h1>Star Wars People</h1>
  <button (click)="swapiService.getSwapiPeople()">Fetch them</button>
  <p *ngIf="swapiService.showLoading | async">Loading...</p>
  <p *ngIf="(swapiService.swapiStatus | async) === 'error'">Yikes, we ran into some trouble. Try again, please</p>
  <ul *ngIf="(swapiService.swapiStatus | async) === 'fetching' || (swapiService.swapiStatus | async) === 'loaded'">
    <li *ngFor="let person of (swapiService.swapiData | async)">
      {{ person.name }}
    </li>
  </ul>
</main>

<div class="header">
  <app-header></app-header>
</div>
